# Site settings
title: DavidOS Documentation
description: "Installation instructions for DavidOS"

# Theme settings
remote_theme: "pmarsceill/just-the-docs"

footer_content: "Copyright &copy; 2025 David. Distributed by an <a href=\"https://github.com/David-dev-web\">Indie OS Developer</a>. | <a href=\"javascript:showThemeChooser( )\">Change Theme</a>"
