theme: jekyll-theme-cayman
title: Welcome to DavidOS
description: The official installation guide and download page for DavidOS.
show_header_links: true
header_links:
  - title: Home
    url: /davidOS-docs/
  - title: Roadmap
    url: /davidOS-docs/roadmap
  - title: About Me
    url: /davidOS-docs/about
