# Site settings
title: DavidOS Documentation
description: "Installation instructions for DavidOS"

# Theme settings
remote_theme: "pmarsceill/just-the-docs"

footer_content: "Copyright &copy; 2025 David."
