theme: jekyll-theme-cayman
title: DavidOS
description: The official installation guide and download page for DavidOS.

# Lädt deine benutzerdefinierten CSS- und JS-Dateien
header_scripts:
  - /assets/css/custom.scss
footer_scripts:
  - /assets/js/main.js
