# Site settings
title: DavidOS Documentation
description: "Installation instructions for DavidOS"

# Theme settings
remote_theme: "pmarsceill/just-the-docs"

# Footer content - WIR LASSEN DEN LINK HIER WEG, UM FEHLER ZU VERMEIDEN
footer_content: "Copyright &copy; 2025 David. Distributed by an <a href=\"https://github.com/David-dev-web\">Indie OS Developer</a>."
