# Wir wechseln zum stabilen, einfachen Theme
theme: jekyll-theme-minimal

# Wir geben der Seite einen Titel
title: DavidOS Documentation & Download
description: The official installation guide and download page for DavidOS.
